#!/usr/bin/env bash

# Unofficial bash strict mode
# For more info, see: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# filePath=$(readlink -f $0)
# dirName=$(dirname "${filePath}")
# fileName=$(basename "$filePath")
# presentDir=$(pwd)

echo "Starting..."

echo "Done!"