#!/usr/bin/env bash

# Unofficial bash strict mode
# For more info, see: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

echo "Starting site build..."

presentDir=$(pwd)
glossarySource="$presentDir/build/glossary.json"

if [[ ! -f "$glossarySource" ]]; then
    echo "No glossary json found!"
    "$presentDir/tools/finance-glossary-build" json
    exit 1
else
    echo glossary found
fi

siteSource="$presentDir/tools/finance-glossary/src"
buildTarget="$presentDir/build/finance-glossary"

if [[ ! -d "$buildTarget" ]]; then
    echo "Creating directory..."
    mkdir "$buildTarget"
fi

cp --update --target-directory="$buildTarget" "$siteSource"/*
cp --update --target-directory="$buildTarget" "$glossarySource"
cp --update --target-directory="$buildTarget" "$presentDir/tools/finance-glossary/scripts/start"
chmod u+x "$presentDir/tools/finance-glossary/scripts/start"