#!/usr/bin/env bash

# Unofficial bash strict mode
# For more info, see: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

siteSource="./tools/finance-glossary/src"
buildTarget="./build/glossary.json"

echo "Starting glossary json grab..."

cp --update --target-directory="$siteSource" "$buildTarget"

echo "Done!"
