#!/usr/bin/awk -f

BEGIN {
    dQuote = "\""
    indent = "  "
}
/^# / {
    word = substr($0, 3)
}
/^## Definition/ {
    while (getline && $0 == "") {}
    # Escape latex sentinels - must come first to avoid catching quote escapes
    gsub(/\\/, "\\\\", $0)
    # Escape double quotes
    gsub(/"/, "\\\"", $0)
    def = $0
}
/^## Tags/ {
    while (getline && $0 == "") {}
    tags = $0
}
END {
    print "{"
    print indent dQuote "word" dQuote ": " dQuote word dQuote ","
    print indent dQuote "definition" dQuote ": " dQuote def dQuote ","
    print indent dQuote "tagString" dQuote ": " dQuote tags dQuote
    print "},"
}
