#!/usr/bin/env bash

# Unofficial bash strict mode
# For more info, see: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

echo "Starting..."
pwd=$(pwd)
npx serve "$pwd/build/finance-glossary"
echo "Done!"